install.packages("shiny")
install.packages("shinydashboard")
install.packages("shinyWidgets")
install.packages("shinyjs")
install.packages("markdown")
install.packages("MASS")
install.packages("pheatmap")
install.packages("plotly")
install.packages("RColorBrewer")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("heatmaply")
install.packages("gridExtra")
install.packages("gtools")
install.packages("colourpicker")
install.packages("Rtsne")
install.packages("scatterplot3d")
install.packages("grid")
install.packages("cowplot")
install.packages("reshape2")
install.packages("rintrojs")
install.packages("uwot")
install.packages("shinyalert")
install.packages("shinycssloaders")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("edgeR")
BiocManager::install("fgsea")
BiocManager::install("DESeq2")


